/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 02:23:51 GMT 2019
 */

package com.test.applications.qmclotserver;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.applications.qmclotserver.otherPost;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class otherPost_ESTest extends otherPost_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      otherPost otherPost0 = new otherPost();
      MockFile mockFile0 = new MockFile("G;DWKPTBI71~#", "=#IZB:I+A2#3lou2]]Q");
      mockFile0.createNewFile();
      // Undeclared exception!
      try { 
        otherPost0.otherRqt(mockFile0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/poi/ss/usermodel/WorkbookFactory
         //
         verifyException("com.test.applications.qmclotserver.readExcel", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      otherPost otherPost0 = new otherPost();
      MockFile mockFile0 = new MockFile("G;DWKPTBI71~#", "=#IZB:I+A2#3lou2]]Q");
      otherPost0.otherRqt(mockFile0);
      assertEquals(0L, mockFile0.lastModified());
  }
}
