/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 03:00:24 GMT 2019
 */

package com.test.applications.qmclotserver;

import org.junit.Test;
import static org.junit.Assert.*;
import com.test.applications.qmclotserver.testPost;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class testPost_ESTest extends testPost_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[1];
      testPost.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      testPost testPost0 = new testPost();
      String string0 = testPost0.transport("?", "?");
      assertEquals("", string0);
  }
}
