/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 03:05:30 GMT 2019
 */

package com.test.selenium;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.selenium.ChromeSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ChromeSet_ESTest extends ChromeSet_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:\\work\\file\\\u8FD9\u4E2A\u6587\u4EF6\u5939 \u4ECA\u5929\u5F00\u59CB\u5C5E\u4E8E\u6211\\\u65B0\u4EBA\u5DE5\u4F5C\u5E38\u7528\u8F6F\u4EF6\\chromedriver.exe");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "rAdXWu,!>8=]L8");
      String[] stringArray0 = new String[8];
      // Undeclared exception!
      try { 
        ChromeSet.main(stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/http/config/RegistryBuilder
         //
         verifyException("org.openqa.selenium.remote.internal.HttpClientFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[5];
      try { 
        ChromeSet.main(stringArray0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // The driver executable does not exist: D:\\work\\file\\\u8FD9\u4E2A\u6587\u4EF6\u5939 \u4ECA\u5929\u5F00\u59CB\u5C5E\u4E8E\u6211\\\u65B0\u4EBA\u5DE5\u4F5C\u5E38\u7528\u8F6F\u4EF6\\chromedriver.exe
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ChromeSet chromeSet0 = new ChromeSet();
  }
}
