/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 02:57:26 GMT 2019
 */

package com.test.arr;

import org.junit.Test;
import static org.junit.Assert.*;
import com.test.arr.arrNew;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class arrNew_ESTest extends arrNew_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      arrNew arrNew0 = new arrNew();
      arrNew0.sortInsert();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      arrNew arrNew0 = new arrNew();
      arrNew0.sum();
  }
}
