/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 03:11:43 GMT 2019
 */

package com.test.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import com.test.controller.MyController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MyController_ESTest extends MyController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MyController myController0 = new MyController();
      String string0 = myController0.welcome();
      assertEquals("/welcome", string0);
  }
}
