/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 02:41:23 GMT 2019
 */

package com.test.worldCup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.worldCup.write;
import java.io.File;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class write_ESTest extends write_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      write write0 = new write();
      MockFile mockFile0 = new MockFile("", "");
      write0.file = (File) mockFile0;
      // Undeclared exception!
      try { 
        write0.writeTxt("agQ..8^W{f&5e");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Writer", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      write write0 = new write();
      write0.writeTxt("(@(7o3'9h");
      ArrayList arrayList0 = write0.readFileByLines();
      assertFalse(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      write write0 = new write();
      write0.file = null;
      // Undeclared exception!
      try { 
        write0.readFileByLines();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      write write0 = new write();
      FileSystemHandling.shouldAllThrowIOExceptions();
      write0.writeTxt("XjraEu-<}G\"|l");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      write write0 = new write();
      ArrayList arrayList0 = write0.readFileByLines();
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      write write0 = new write();
      write0.writeTxt("(@(7o3'9h");
      write0.writeTxt("(@(7o3'9h");
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      write write0 = new write();
      write0.writeTxt("");
      // Undeclared exception!
      try { 
        write0.writeTxt("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      write write0 = new write();
      write0.writeTxt("XjraEu-<}G\"|l");
      FileSystemHandling.shouldAllThrowIOExceptions();
      ArrayList arrayList0 = write0.readFileByLines();
      assertTrue(arrayList0.isEmpty());
  }
}
