/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 02:46:42 GMT 2019
 */

package com.test.applications;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.applications.readTxt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class readTxt_ESTest extends readTxt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[6];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:\\work\\environment\\IdeaProjects\\testtwo\\C:\\Users\\Administrator\\Desktop\\phone.txt");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Y)~_T");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "ContentType");
      // Undeclared exception!
      try { 
        readTxt.main(stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/httpclient/HttpMethod
         //
         verifyException("com.test.applications.readTxt", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockFile mockFile0 = new MockFile("J~LcqHJZT7&C");
      String string0 = readTxt.txt2String(mockFile0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[3];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:\\work\\environment\\IdeaProjects\\testtwo\\C:\\Users\\Administrator\\Desktop\\phone.txt");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      // Undeclared exception!
      try { 
        readTxt.main(stringArray0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.test.applications.readTxt", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:\\work\\environment\\IdeaProjects\\testtwo\\V\\.`*VS@%{0[`}bVsp~>;");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "C:UsersAdministratorDesktopphone.txt");
      MockFile mockFile0 = new MockFile("V");
      MockFile mockFile1 = new MockFile(mockFile0, ".`*VS@%{0[`}bVsp~>;");
      String string0 = readTxt.txt2String(mockFile1);
      assertEquals("FGFC:UsersAdministratorDesktopphone.txt", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      readTxt readTxt0 = new readTxt();
  }
}
