/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 02:50:08 GMT 2019
 */

package com.test.worldCup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.worldCup.getHTML;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class getHTML_ESTest extends getHTML_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      getHTML getHTML0 = new getHTML();
      getHTML0.setPageUrl("/W>M");
      getHTML0.getPageUrl();
      assertEquals("UTF8", getHTML0.getPageEncode());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      getHTML getHTML0 = new getHTML();
      getHTML0.setPageUrl("");
      getHTML0.getPageUrl();
      assertEquals("UTF8", getHTML0.getPageEncode());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      getHTML getHTML0 = new getHTML();
      getHTML0.setPageEncode((String) null);
      String string0 = getHTML0.getPageEncode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      getHTML getHTML0 = new getHTML();
      getHTML0.setPageEncode("");
      String string0 = getHTML0.getPageEncode();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      getHTML getHTML0 = new getHTML();
      // Undeclared exception!
      try { 
        getHTML0.getPageSourceWithoutHtml();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/poi/ss/usermodel/Row
         //
         verifyException("com.test.worldCup.getHTML", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      getHTML getHTML0 = new getHTML();
      String string0 = getHTML0.getPageSource();
      getHTML0.setPageUrl(string0);
      assertEquals("UTF8", getHTML0.getPageEncode());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      getHTML getHTML0 = new getHTML();
      String string0 = getHTML0.getPageEncode();
      assertEquals("UTF8", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      getHTML getHTML0 = new getHTML();
      getHTML0.getPageUrl();
      assertEquals("UTF8", getHTML0.getPageEncode());
  }
}
