/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 02:34:40 GMT 2019
 */

package com.test.applications.qmclotserver;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.applications.qmclotserver.otherPost1;
import java.io.File;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class otherPost1_ESTest extends otherPost1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      otherPost1 otherPost1_0 = new otherPost1();
      MockFile mockFile0 = new MockFile("", "JSON keys cannot be null.");
      File file0 = MockFile.createTempFile("87G+`Q&", "", (File) mockFile0);
      // Undeclared exception!
      try { 
        otherPost1_0.otherSedRqt(file0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/poi/ss/usermodel/WorkbookFactory
         //
         verifyException("com.test.applications.qmclotserver.readExcel", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      otherPost1 otherPost1_0 = new otherPost1();
      MockFile mockFile0 = new MockFile("@2ND");
      MockFile mockFile1 = new MockFile(mockFile0, "");
      mockFile1.mkdir();
      mockFile1.createNewFile();
      mockFile0.delete();
      // Undeclared exception!
      try { 
        otherPost1_0.otherRqt(mockFile1);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/poi/ss/usermodel/WorkbookFactory
         //
         verifyException("com.test.applications.qmclotserver.readExcel", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      otherPost1 otherPost1_0 = new otherPost1();
      MockFile mockFile0 = new MockFile("", "");
      otherPost1_0.otherSedRqt(mockFile0);
      assertFalse(mockFile0.isFile());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      otherPost1 otherPost1_0 = new otherPost1();
      MockFile mockFile0 = new MockFile("", "");
      otherPost1_0.otherRqt(mockFile0);
      assertTrue(mockFile0.canExecute());
  }
}
