/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 02:37:25 GMT 2019
 */

package com.test.applications.qmclotserver;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.applications.qmclotserver.readExcel;
import java.io.File;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class readExcel_ESTest extends readExcel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockFile mockFile0 = new MockFile("org.json.JSONException", "org.json.JSONException");
      File file0 = MockFile.createTempFile("W?^22EJtWFt>gi2", "", (File) mockFile0);
      // Undeclared exception!
      try { 
        readExcel.readExcelReturnarrArr(file0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/poi/ss/usermodel/WorkbookFactory
         //
         verifyException("com.test.applications.qmclotserver.readExcel", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[9];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:\\work\\environment\\IdeaProjects\\testtwo\\C:\\Users\\user\\Desktop\\test.xlsx");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "");
      // Undeclared exception!
      try { 
        readExcel.main(stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/poi/ss/usermodel/WorkbookFactory
         //
         verifyException("com.test.applications.qmclotserver.readExcel", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockFile mockFile0 = new MockFile("org.json.JSONException", "org.json.JSONException");
      String[][] stringArray0 = readExcel.readExcelReturnarrArr(mockFile0);
      assertNotNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      readExcel readExcel0 = new readExcel();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[1];
      readExcel.main(stringArray0);
  }
}
