/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 03:09:17 GMT 2019
 */

package com.test.applications.katalon;

import org.junit.Test;
import static org.junit.Assert.*;
import com.test.applications.katalon.testcase2;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class testcase2_ESTest extends testcase2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      testcase2 testcase2_0 = new testcase2();
      testcase2_0.testSelenium();
  }
}
