/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 03:04:47 GMT 2019
 */

package com.test.uploadFile;

import org.junit.Test;
import static org.junit.Assert.*;
import com.test.uploadFile.saveFile;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class saveFile_ESTest extends saveFile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      saveFile saveFile0 = new saveFile();
      String string0 = saveFile0.saveFile();
      assertEquals("wancheng", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      saveFile saveFile0 = new saveFile();
      String string0 = saveFile0.winOrLin();
      assertEquals("windows", string0);
  }
}
