/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 03:06:56 GMT 2019
 */

package com.test.applications;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.applications.phonePlace;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class phonePlace_ESTest extends phonePlace_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[4];
      // Undeclared exception!
      try { 
        phonePlace.main(stringArray0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // The driver executable does not exist: D:\\work\\file\\\u8FD9\u4E2A\u6587\u4EF6\u5939 \u4ECA\u5929\u5F00\u59CB\u5C5E\u4E8E\u6211\\\u65B0\u4EBA\u5DE5\u4F5C\u5E38\u7528\u8F6F\u4EF6\\chromedriver.exe
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      phonePlace phonePlace0 = new phonePlace();
      // Undeclared exception!
      try { 
        phonePlace0.search("fo1(IHQkN/0r%G");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // The driver executable does not exist: D:\\work\\file\\\u8FD9\u4E2A\u6587\u4EF6\u5939 \u4ECA\u5929\u5F00\u59CB\u5C5E\u4E8E\u6211\\\u65B0\u4EBA\u5DE5\u4F5C\u5E38\u7528\u8F6F\u4EF6\\chromedriver.exe
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }
}
