/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 02:58:34 GMT 2019
 */

package com.test.applications;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.applications.test;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class test_ESTest extends test_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[5];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:\\work\\environment\\IdeaProjects\\testtwo\\C:\\Users\\Administrator\\AppData\\Local\\Google\\Chrome\\Application\\chromedriver.exe");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "by$];=v^C`TSJ");
      // Undeclared exception!
      try { 
        test.main(stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/http/config/RegistryBuilder
         //
         verifyException("org.openqa.selenium.remote.internal.HttpClientFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      test test0 = new test();
      try { 
        test0.test();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.test.applications.test", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[1];
      test.main(stringArray0);
  }
}
