/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 03:10:50 GMT 2019
 */

package com.test.sometest;

import org.junit.Test;
import static org.junit.Assert.*;
import com.test.sometest.Dog;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Dog_ESTest extends Dog_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Dog dog0 = new Dog();
      dog0.stop();
      assertNull(dog0.getColor());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Dog dog0 = new Dog();
      dog0.move();
      assertNull(dog0.getColor());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Dog dog0 = new Dog();
      dog0.start();
      assertNull(dog0.getColor());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Dog dog0 = new Dog();
      dog0.cry();
      assertNull(dog0.getColor());
  }
}
