/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 03:09:05 GMT 2019
 */

package com.test.sometest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.sometest.testSelenium;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class testSelenium_ESTest extends testSelenium_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      testSelenium testSelenium0 = new testSelenium();
      // Undeclared exception!
      try { 
        testSelenium0.testsele((String) null);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // The driver executable does not exist: D:\\work\\environment\\IdeaProjects\\testtwo\\C:\\Users\\Administrator\\AppData\\Local\\Google\\Chrome\\Application\\chromedriver.exe
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }
}
