/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 03:06:12 GMT 2019
 */

package com.test.sometest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.sometest.testread;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class testread_ESTest extends testread_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:\\work\\environment\\IdeaProjects\\testtwo\\C:\\Users\\user\\Desktop\\test1.xlsx");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "rzz;!2");
      testread testread0 = new testread();
      // Undeclared exception!
      try { 
        testread0.testread();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/poi/ss/usermodel/WorkbookFactory
         //
         verifyException("com.test.sometest.testread", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[7];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:\\work\\environment\\IdeaProjects\\testtwo\\C:\\Users\\user\\Desktop\\test1.xlsx");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "p+z");
      // Undeclared exception!
      try { 
        testread.main(stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/poi/ss/usermodel/WorkbookFactory
         //
         verifyException("com.test.sometest.testread", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[7];
      testread.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      testread testread0 = new testread();
      testread0.testread();
  }
}
