/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 03:10:38 GMT 2019
 */

package com.test.sometest;

import org.junit.Test;
import static org.junit.Assert.*;
import com.test.sometest.Dog;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Animal_ESTest extends Animal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Dog dog0 = new Dog();
      dog0.cry();
      assertNull(dog0.getColor());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Dog dog0 = new Dog();
      dog0.color = "";
      String string0 = dog0.getColor();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Dog dog0 = new Dog();
      dog0.name();
      assertNull(dog0.getColor());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Dog dog0 = new Dog();
      dog0.setColor("z3-|G_'fF[");
      String string0 = dog0.getColor();
      assertEquals("z3-|G_'fF[", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Dog dog0 = new Dog();
      String string0 = dog0.getColor();
      assertNull(string0);
  }
}
