/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 02:54:45 GMT 2019
 */

package com.test.applications.qmclotserver.overwrite11x5;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.applications.qmclotserver.overwrite11x5.arrtoNN;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class arrtoNN_ESTest extends arrtoNN_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      arrtoNN arrtoNN0 = new arrtoNN();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "PV>OU7-ca\r%^GG'3";
      stringArray0[1] = "";
      stringArray0[2] = "";
      arrtoNN.main(stringArray0);
      arrtoNN.main(stringArray0);
      int[] intArray0 = new int[5];
      intArray0[0] = 0;
      intArray0[1] = 3;
      intArray0[2] = 0;
      // Undeclared exception!
      arrtoNN0.combine_increase(stringArray0, 1, intArray0, 5, 0, 3121);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "6=-.s#!}2dSf=wG1%";
      stringArray0[1] = "";
      stringArray0[2] = "2";
      stringArray0[3] = "";
      stringArray0[4] = "";
      stringArray0[5] = "";
      stringArray0[6] = ".`1 o$diO_=: 1";
      stringArray0[7] = "";
      arrtoNN.main(stringArray0);
      arrtoNN.main(stringArray0);
      arrtoNN arrtoNN0 = new arrtoNN();
      arrtoNN.main(stringArray0);
      arrtoNN.main(stringArray0);
      int[] intArray0 = new int[1];
      intArray0[0] = 0;
      arrtoNN0.combine_increase(stringArray0, (-1463), intArray0, 1, 1, (-1463));
      assertArrayEquals(new int[] {0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      arrtoNN arrtoNN0 = new arrtoNN();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "3";
      stringArray0[1] = "Mof62{CGi)";
      stringArray0[2] = "x,";
      stringArray0[3] = "K#r=u!VkKi";
      // Undeclared exception!
      try { 
        arrtoNN0.combine_increase(stringArray0, 0, (int[]) null, 0, 0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.test.applications.qmclotserver.overwrite11x5.arrtoNN", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      arrtoNN arrtoNN0 = new arrtoNN();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "{u";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "&lWpf:";
      int[] intArray0 = new int[2];
      intArray0[0] = 1;
      intArray0[1] = 1;
      // Undeclared exception!
      try { 
        arrtoNN0.combine_increase(stringArray0, 1, intArray0, 5216, 0, 5217);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      arrtoNN arrtoNN0 = new arrtoNN();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "4@*@x$9t[h<r";
      int[] intArray0 = new int[0];
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrtoNN0.b = arrayList0;
      // Undeclared exception!
      try { 
        arrtoNN0.combine_increase(stringArray0, 0, intArray0, 0, 0, 203);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      arrtoNN.main((String[]) null);
      arrtoNN arrtoNN0 = new arrtoNN();
      int[] intArray0 = new int[0];
      arrtoNN0.combine_increase((String[]) null, (-1), intArray0, (-1), (-1), (-2108));
      assertArrayEquals(new int[] {}, intArray0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      arrtoNN arrtoNN0 = new arrtoNN();
      arrtoNN.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[16];
      arrtoNN.main(stringArray0);
  }
}
