/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 02:56:12 GMT 2019
 */

package com.test.applications.qmclotserver.overwrite11x5;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.test.applications.qmclotserver.overwrite11x5.renxuanTwo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class renxuanTwo_ESTest extends renxuanTwo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      renxuanTwo renxuanTwo0 = new renxuanTwo();
      // Undeclared exception!
      try { 
        renxuanTwo0.singleBet2("+n4,86Vge@f", "+n4,86Vge@f", "+n4,86Vge@f");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"+n4,86Vge@f\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      renxuanTwo renxuanTwo0 = new renxuanTwo();
      renxuanTwo0.singleBet2("-|&F>dqFi", "2018011230", "~,8|vp0(4");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      renxuanTwo renxuanTwo0 = new renxuanTwo();
      renxuanTwo0.mutipBet2();
  }
}
